# Stress testing control plane components
# TODO: gabe should fill me in wiht more info

# Size of test variables
{{$namespaces := DefaultParam .CL2_NAMESPACES 1}}
{{$nodegroups := DefaultParam .CL2_NODEGROUPS 1}}
{{$clns := DefaultParam .CL2_CLUSTER_NAMESPACE "missing-k8s"}}
{{$replicas := DefaultParam .CL2_REPLICAS 300 }}
{{$maxScaleFactor := DefaultParam .CL2_MAX_SCALE_FACTOR 3}}
{{$numWatcherReplicas:= DefaultParam .CL2_WATCHER_REPLICAS 100 }}

name: control-plane-load-1
namespace:
  number: {{$namespaces}}
tuningSets:
  - name: Sequence
    parallelismLimitedLoad:
      parallelismLimit: 1
  - name: SequenceStepped
    steppedLoad:
      burstSize: 1
      stepDelay: 15s

steps:
  - name: Create RBAC
    phases:
      - namespaceRange:
          min: 1
          max: {{$namespaces}}
        replicasPerNamespace: 1
        tuningSet: SequenceStepped
        objectBundle:
          - basename: watcher
            objectTemplatePath: serviceaccount.yaml
          - basename: watcher
            objectTemplatePath: role.yaml
          - basename: watcher
            objectTemplatePath: rolebinding.yaml
            templateFillMap:
              ServiceAccount: watcher-0

  - name: Start measurements
    # TODO: also gather these values
    measurements:
    - Identifier: APIResponsivenessPrometheus
      Method: APIResponsivenessPrometheus
      Params:
        action: start
    - Identifier: APIResponsivenessPrometheusSimple
      Method: APIResponsivenessPrometheus
      Params:
        action: start
    - Identifier: InClusterNetworkLatency
      Method: InClusterNetworkLatency
      Params:
        action: start
        replicasPerProbe: {{AddInt 2 (DivideInt .Nodes 100)}}
    - Identifier: DnsLookupLatency
      Method: DnsLookupLatency
      Params:
        action: start
        replicasPerProbe: {{AddInt 2 (DivideInt .Nodes 100)}}

  - name: Creating Nodegroups
    phases:
{{range $i := Loop $nodegroups}}
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 1
      tuningSet: SequenceStepped
      objectBundle:
        - basename: ng-{{$i}}
          objectTemplatePath: nodegroup.yaml
          templateFillMap:
            Size: 30
{{ end }}

  - name: Waiting for initial nodes to be running
    measurements:
    - Identifier: WaitForNodes
      Method: WaitForNodes
      Params:
        maxDesiredNodeCount: 2500
        # minDesiredNodeCount:  {{ MultiplyInt 3 (MultiplyInt $nodegroups $namespaces)}}
        minDesiredNodeCount:  {{ MultiplyInt $nodegroups $namespaces}} # Third of the nodes because it takes too long when lot of ng are created
        action: gather
        labelSelector: test = perf-tests
        timeout: 10m

  - name: Measure pod launch time
    measurements:
    - Identifier: WaitForRunningPods
      Method: WaitForControlledPodsRunning
      Params:
        action: start
        apiVersion: apps/v1
        kind: Deployment
        checkIfPodsAreUpdated: false
        labelSelector: test = perf-tests
        operationTimeout: 20m

  - name: Launch watcher pods
    phases:
{{range $i := Loop $nodegroups}}
      - namespaceRange:
          min: 1
          max: {{$namespaces}}
        replicasPerNamespace: 1
        tuningSet: Sequence
        objectBundle:
          - basename: watcher
            objectTemplatePath: watcher.yaml
            templateFillMap:
              Replicas: {{$numWatcherReplicas}}
              Taint: ng-{{$i}}
{{end}}

  - name: Waiting for watcher pods
    measurements:
    - Identifier: WaitForRunningPods
      Method: WaitForControlledPodsRunning
      Params:
        action: gather

  - name: Creating pods to simulate deployments ({{$replicas}})
    phases:
{{range $i := Loop $nodegroups}}
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 1
      tuningSet: Sequence
      objectBundle:
      - basename: pause
        objectTemplatePath: deployment.yaml
        templateFillMap:
          Replicas: {{$replicas}}
          Taint: ng-{{$i}}
{{end}}

  - name: Waiting for load pods to be ready
    measurements:
    - Identifier: WaitForRunningPods
      Method: WaitForControlledPodsRunning
      Params:
        action: gather
    - Identifier: Wait # wait for pod launches to settle for a few minutes
      Method: Sleep
      Params:
        duration: 20s


  - name: Scale-up pods to {{MultiplyInt $maxScaleFactor $replicas}}
    phases:
{{range $i := Loop $nodegroups}}
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 1
      tuningSet: Sequence
      objectBundle:
      - basename: pause
        objectTemplatePath: deployment.yaml
        templateFillMap:
          Replicas: {{MultiplyInt $maxScaleFactor $replicas}}
          Taint: ng-{{$i}}
{{end}}

  - name: Waiting for pods to be running L147
    measurements:
    - Identifier: WaitForRunningPods
      Method: WaitForControlledPodsRunning
      Params:
        action: gather
    - Identifier: Wait # wait for pod launches to settle for a few minutes
      Method: Sleep
      Params:
        duration: 30s

  - name: Scale-down pods L165
    phases:
{{range $i := Loop $nodegroups}}
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 1
      tuningSet: Sequence
      objectBundle:
      - basename: pause
        objectTemplatePath: deployment.yaml
        templateFillMap:
          Replicas: {{$replicas}}
          Taint: ng-{{$i}}
{{end}}

  - name: Waiting for pods to be running
    measurements:
    - Identifier: WaitForRunningPods
      Method: WaitForControlledPodsRunning
      Params:
        action: gather


  - name: Deleting pods
    phases:
{{range $i := Loop $nodegroups}}
      - namespaceRange:
          min: 1
          max: {{$namespaces}}
        replicasPerNamespace: 0
        tuningSet: Sequence
        objectBundle:
        - basename: pause
          objectTemplatePath: deployment.yaml
          templateFillMap:
            Replicas: 0
            Taint: ng-{{$i}}
      - namespaceRange:
          min: 1
          max: {{$namespaces}}
        replicasPerNamespace: 0
        tuningSet: Sequence
        objectBundle:
        - basename: watcher
          objectTemplatePath: watcher.yaml
          templateFillMap:
            Replicas: 0
            Taint: ng-{{$i}}
{{ end }}

  - name: Waiting for pods to be deleted
    measurements:
    - Identifier: WaitForRunningPods
      Method: WaitForControlledPodsRunning
      Params:
        action: gather
    - Identifier: Wait # let pods get cleaned up before we try to axe the NG
      Method: Sleep
      Params:
        duration: 2m


  - name: Deleting nodegroups
    phases:
{{range $i := Loop $nodegroups}}
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 0
      tuningSet: SequenceStepped
      objectBundle:
      - basename: ng-{{$i}}
        objectTemplatePath: nodegroup.yaml
        templateFillMap:
          Size: 30
{{ end }}

