---
apiVersion: datadoghq.com/v1
kind: NodeGroup
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"
  annotations:
    nodegroups.datadoghq.com/delete: "I-have-checked-that-no-workload-runs-on-nodes-before-deleting-this-ng-because-i-do-not-want-to-cause-another-sev1-incident"
  labels:
    team: compute
    test: perf-tests
spec:
  options:
    clusterAutoscalerOptions:
      maxSize: 255
      minSize: {{.Size}}
      initialSize: {{.Size}}
  azure:
    virtualMachineScaleSetSKU:
      name: Standard_DS3_v2
  aws:
    group:
      minSize: {{.Size}}
      maxSize: 255
    launchConfiguration:
      instanceType: t2.large
  kubelet:
    taints:
      node: "{{ .Name }}:NoSchedule"
    labels:
      test: perf-tests
      nodegroup-name: "{{ .Name }}"
      nodegroups.datadoghq.com/namespace: "{{ .Namespace }}"
      nodegroups.datadoghq.com/name: "{{ .Name }}"
