---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"
subjects:
- kind: ServiceAccount
  name: "{{ .ServiceAccount }}"
  namespace: "{{ .Namespace }}"
roleRef:
  kind: Role
  name: "{{ .Name }}"
  apiGroup: rbac.authorization.k8s.io
